name: healthy_pet_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  connectivity_plus: ^5.0.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  intl: ^0.18.1
  pinput: ^3.0.1
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login/

  fonts:
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
        - asset: fonts/MavenPro-Bold.ttf
          weight: 700
        - asset: fonts/MavenPro-Black.ttf
          weight: 900
    - family: Lemonada
      fonts:
        - asset: fonts/Lemonada-Regular.ttf
        - asset: fonts/Lemonada-Light.ttf
          weight: 300
        - asset: fonts/Lemonada-Bold.ttf
          weight: 700